spring.application.name=minesweeper-sb3
spring.main.banner-mode=off
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
games.file.path=Task3/src/main/resources/dbfile/games.txt
game-results.file.path=Task3/src/main/resources/dbfile/game-results.txt