plugins {
    id 'java'
    id 'application'
}

group = 'by.shift.chat'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

ext {
    versions = [
            jackson: "2.20.1",
            lombok : "1.18.42",
            slf4j  : "2.0.17",
            logback: "1.5.21",
            junit  : "5.10.0",
            assertj: "3.27.6"
    ]
}

dependencies {
    implementation "com.fasterxml.jackson.core:jackson-databind:${versions.jackson}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${versions.jackson}"

    compileOnly("org.projectlombok:lombok:${versions.lombok}")
    annotationProcessor("org.projectlombok:lombok:${versions.lombok}")

    implementation "org.slf4j:slf4j-api:${versions.slf4j}"
    implementation "ch.qos.logback:logback-classic:${versions.logback}"

    testImplementation("org.junit.jupiter:junit-jupiter:${versions.junit}")
    testImplementation "org.assertj:assertj-core:${versions.assertj}"

}

test {
    useJUnitPlatform()
}

tasks.register('serverJar', Jar) {
    group = 'build'

    archiveBaseName.set("${project.name}-server")
    archiveVersion.set("${project.version}")

    from(sourceSets.main.output) {
        include 'by/shift/chat/common/**'
        include 'by/shift/chat/server/**'
    }

    from('src/main/resources') {
        include 'logback.xml'
        include 'server.properties'
    }

    manifest {
        attributes 'Main-Class': 'by.shift.chat.server.ServerStarter'
    }

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.register('clientJar', Jar) {
    group = 'build'

    archiveBaseName.set("${project.name}-client")
    archiveVersion.set("${project.version}")

    from(sourceSets.main.output) {
        include 'by/shift/chat/common/**'
        include 'by/shift/chat/client/**'
    }

    from('src/main/resources') {
        include 'logback.xml'
    }

    manifest {
        attributes 'Main-Class': 'by.shift.chat.client.ClientStarter'
    }

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('build') {
    dependsOn tasks.named('serverJar')
    dependsOn tasks.named('clientJar')
}